### ISSUE TITLE
Добавить в article поле автор

### ISSUE THREAD

**Issue by skyndfly** [skyndfly/junior-blog#54]
Тут есть два варианта или мы делаем отдельную таблицу и CRUD к авторам, и в записях просто через выпадающий список выбирать автора.
Или же, лучше вставлять логин админа.
Или третий вариант просто заполнять это поле вручную. 
Твои идеи ?

**Comment by vasilychapaev** [comment]
1. т.к. автор не может быть незареганным юзером (зачем позволять постить анонимам/под другим юзером...хз)
- значит юзер будет из зареганных

2. поскольку это CMS - то она должна помогать управлять контентом, 
- значит ручной ввод надо минимизировать, 
- значит делаем select из существующих юзеров

3. сейчас вижу смысл сделать проще
- добавить user_id в articles
- если будем усложнять (несколько сущностей постов, например видео - то можно будет сделать morph-связи)

**Comment by skyndfly** [comment]
В данном случае админка, это место постинга только для владельцев сайта, и поэтому имеет смысл как владельцу дать возможность поститься под любым именем. Странно будет если я создаю пост и могу поставить любого юзера. 
Или же, пусть подставляеться имя(юзернейм) админа и все без возможности выбора
Когда уже будет в личном кабинете юзера создавать от себя посты, то тогда тоже нет надобности в селекте, так как должно подставлять его имя(юзернейм)

**Comment by vasilychapaev** [comment]
я тогда не понимаю логику, как будет постить юзер, если у него нету доступа к админке
- сделал сохранение с admin_id
- добавил отображение в article
- починил баг с сохранением status

**Comment by vasilychapaev** [comment]
туплю как коммит/PR привязать к этому обсуждению
